import * as THREE from 'three';
import {RACERS} from './data.js';
import {createRacerModel} from './models.js';
import {GameUI,Input} from './ui.js';

const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),wrap=v=>((v%1)+1)%1;
class TestTrack{
  constructor(scene){this.width=13;this.group=new THREE.Group();scene.add(this.group);this.build();}
  sample(progress,lane=0){const a=wrap(progress)*TAU,x=Math.cos(a)*38,z=Math.sin(a)*26;const tangent=new THREE.Vector3(-38*Math.sin(a),0,26*Math.cos(a)).normalize();const normal=new THREE.Vector3(-tangent.z,0,tangent.x);return{position:new THREE.Vector3(x,0,z).addScaledVector(normal,lane),tangent,normal,angle:Math.atan2(tangent.x,tangent.z)}}
  ribbon(width,y,color){const verts=[],idx=[],n=240;for(let i=0;i<=n;i++){const s=this.sample(i/n),h=width/2,l=s.position.clone().addScaledVector(s.normal,-h),r=s.position.clone().addScaledVector(s.normal,h);verts.push(l.x,y,l.z,r.x,y,r.z)}for(let i=0;i<n;i++){const b=i*2;idx.push(b,b+2,b+1,b+1,b+2,b+3)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.92,side:THREE.DoubleSide}));m.receiveShadow=true;return m}
  build(){const ground=new THREE.Mesh(new THREE.CircleGeometry(92,64),new THREE.MeshStandardMaterial({color:0x1f533a,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.18;ground.receiveShadow=true;this.group.add(ground,this.ribbon(this.width+3,-.04,0xe8edf2),this.ribbon(this.width,.02,0x303541));
    for(let i=0;i<120;i+=8){const s=this.sample(i/120);const dash=new THREE.Mesh(new THREE.BoxGeometry(.18,.06,2.2),new THREE.MeshStandardMaterial({color:0xffffff}));dash.position.copy(s.position);dash.position.y=.08;dash.rotation.y=s.angle;this.group.add(dash)}
    for(const p of[.08,.42,.72]){const s=this.sample(p);for(const l of[-4,0,4]){const pad=new THREE.Mesh(new THREE.BoxGeometry(2.2,.08,4),new THREE.MeshStandardMaterial({color:0x42dffc,emissive:0x14627d,emissiveIntensity:1}));pad.position.copy(s.position).addScaledVector(s.normal,l);pad.position.y=.1;pad.rotation.y=s.angle;pad.userData.boost=true;this.group.add(pad)}}
    const start=this.sample(0);for(let x=-6;x<=6;x+=1.2){for(let z=-1;z<=1;z+=1){const tile=new THREE.Mesh(new THREE.BoxGeometry(1.2,.06,1),new THREE.MeshStandardMaterial({color:(Math.round(x/1.2)+z)%2?0xffffff:0x111827}));tile.position.copy(start.position).addScaledVector(start.normal,x).addScaledVector(start.tangent,z);tile.position.y=.1;tile.rotation.y=start.angle;this.group.add(tile)}}
  }
}
class Racer{
  constructor(def,index,player,track,scene){this.r=def;this.player=player;this.track=track;this.progress=.025-index*.006;this.lap=0;this.lane=(index%2?1:-1)*(1.2+Math.floor(index/2)*.7);this.speed=0;this.targetSpeed=0;this.boost=0;this.drift=0;this.air=0;this.invulnerable=0;this.finished=false;this.finishTime=0;this.model=createRacerModel(def,player);scene.add(this.model.group);this.sync(0)}
  score(){return this.finished?100-this.finishTime/1000:this.lap+this.progress}
  sync(time){const s=this.track.sample(this.progress,this.lane),jump=this.air>0?Math.sin((1-this.air)*Math.PI)*1.5:0;this.model.group.position.copy(s.position);this.model.group.position.y=.5+jump;this.model.group.rotation.y=s.angle;this.model.update(this.speed,time,this.drift>.05)}
}
export class TurboLegendsGame{
  constructor(canvas,root){this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x78c9ff);this.scene.fog=new THREE.Fog(0x78c9ff,80,165);this.camera=new THREE.PerspectiveCamera(62,1,.1,240);this.track=new TestTrack(this.scene);this.racers=[];this.player=null;this.state='menu';this.beforePause='race';this.selected=0;this.countdown=0;this.time=0;this.last=performance.now();this.look=new THREE.Vector3();this.ui=new GameUI(root,{start:i=>this.start(i),pause:()=>this.pause(),resume:()=>this.resume(),menu:()=>this.menu()});this.input=new Input(root);this.lights();this.scenery();this.resize();addEventListener('resize',()=>this.resize(),{passive:true});requestAnimationFrame(t=>this.frame(t));}
  lights(){this.scene.add(new THREE.HemisphereLight(0xd7f4ff,0x264a2e,2.3));const sun=new THREE.DirectionalLight(0xfff1d2,2.8);sun.position.set(-35,65,35);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-75,right:75,top:75,bottom:-75,near:1,far:170});this.scene.add(sun)}
  scenery(){const trunk=new THREE.MeshStandardMaterial({color:0x74492e}),leaf=new THREE.MeshStandardMaterial({color:0x2f8653}),tg=new THREE.CylinderGeometry(.25,.42,2.5,7),lg=new THREE.ConeGeometry(1.4,3.6,8);for(let i=0;i<58;i++){const a=i/58*TAU,r=52+(i%4)*4,g=new THREE.Group(),t=new THREE.Mesh(tg,trunk),l=new THREE.Mesh(lg,leaf);t.position.y=1.25;l.position.y=3.8;t.castShadow=l.castShadow=true;g.add(t,l);g.position.set(Math.cos(a)*r,0,Math.sin(a)*r);this.scene.add(g)}}
  clear(){for(const r of this.racers)this.scene.remove(r.model.group);this.racers=[];this.player=null}
  start(index){this.clear();this.selected=index;this.time=0;this.countdown=3.4;this.state='countdown';const order=[...RACERS];for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}const chosen=RACERS[index],others=order.filter(x=>x.id!==chosen.id),line=[others[0],others[1],others[2],chosen,...others.slice(3,7)];line.forEach((d,i)=>{const r=new Racer(d,i,d.id===chosen.id,this.track,this.scene);this.racers.push(r);if(r.player)this.player=r});this.ui.showRace(index);this.ui.setCountdown('3');this.input.reset();this.snapCamera()}
  frame(now){const dt=Math.min(.1,Math.max(0,(now-this.last)/1000));this.last=now;if(this.state!=='paused'){if(this.state==='menu')this.menuCamera(now);if(this.state==='countdown'||this.state==='race')this.updateRace(dt,now/1000);if(this.state==='finished')this.updateFinish(dt,now/1000)}this.renderer.render(this.scene,this.camera);requestAnimationFrame(t=>this.frame(t))}
  updateRace(dt,t){if(!this.player)return;let drive=this.state==='race';if(this.state==='countdown'){this.countdown-=dt;if(this.countdown>0)this.ui.setCountdown(String(Math.ceil(this.countdown)));else{drive=true;this.ui.setCountdown(this.countdown>-.65?'¡YA!':'');if(this.countdown<=-.65)this.state='race'}}if(drive)this.time+=dt;const input=drive?this.input.sample():{steer:0,drift:false,turbo:false};this.updatePlayer(this.player,input,dt);for(const r of this.racers)if(!r.player)this.updateAI(r,dt,t);this.collisions();for(const r of this.racers){this.specialZones(r);this.advance(r,dt,t)}const standings=this.sorted();const pos=standings.indexOf(this.player)+1;this.ui.update({lap:this.player.lap,position:pos,speed:this.player.speed*5.5,time:this.time,drift:this.player.drift,standings});this.cameraFollow(this.player,dt);if(this.player.finished){this.state='finished';setTimeout(()=>{if(this.state==='finished')this.ui.showFinish(pos,this.player.finishTime,this.sorted())},750)}}
  updatePlayer(r,input,dt){const max=26+r.r.stats[0]*1.75,acc=9+r.r.stats[1]*2.1,handling=.8+r.r.stats[2]*.25;if(r.finished){r.targetSpeed=0;return}r.targetSpeed=driveTarget(max,r.boost);r.speed=Math.min(r.targetSpeed,r.speed+acc*dt);r.lane=clamp(r.lane+input.steer*handling*(input.drift?1.65:1)*dt*5.2,-5.7,5.7);if(input.drift&&Math.abs(input.steer)>.1&&r.speed>12){const gain=r.r.kind==='mara'?1.35:1;r.drift=clamp(r.drift+dt*.7*gain,0,1);r.speed*=Math.pow(.994,dt*60)}else if(r.drift>0){if(r.drift>.35){r.boost=Math.max(r.boost,.45+r.drift*(r.r.kind==='astra'?1.45:1.1));this.ui.message('⚡ ¡Mini-turbo!')}r.drift=0}if(input.turbo&&r.drift>.18){r.boost=Math.max(r.boost,.7+r.drift);r.drift=0;this.ui.message('🔥 Turbo liberado')}if(r.boost>0)r.boost-=dt;r.invulnerable=Math.max(0,r.invulnerable-dt)}
  updateAI(r,dt,t){if(r.finished)return;const max=25+r.r.stats[0]*1.7,skill=.91+(r.r.stats[2]*.012);r.speed+=(max*skill-r.speed)*(1-Math.exp(-2*dt));r.lane+=(Math.sin(t*.45+RACERS.indexOf(r.r)*1.9)*2-r.lane)*(1-Math.exp(-.55*dt));if(Math.random()<.0025+r.r.stats[4]*.00025)r.boost=.8;if(r.boost>0)r.boost-=dt}
  specialZones(r){const p=wrap(r.progress);if(([.08,.42,.72].some(x=>Math.abs(p-x)<.006))&&r.boost<.25){r.boost=r.r.kind==='bujia'?1.5:1.05;if(r.player)this.ui.message('⚡ Plataforma turbo')}if(p>.245&&p<.265&&r.air<=0){r.air=1;if(r.player)this.ui.message('🛫 ¡Salto!')}}
  advance(r,dt,t){if(r.finished){r.speed*=Math.pow(.96,dt*60);r.sync(t);return}const old=r.progress,bonus=r.boost>0?1.28:1;r.progress=wrap(r.progress+r.speed*bonus/230*dt);if(old>.9&&r.progress<.1){r.lap++;if(r.r.kind==='baron')r.boost=1.0;if(r.player&&r.lap<3)this.ui.message(`Vuelta ${r.lap+1}/3`)}if(r.air>0){r.air-=dt*(r.r.kind==='riff'?.75:1);if(r.air<=0&&r.r.kind==='riff')r.boost=1}if(r.lap>=3){r.finished=true;r.finishTime=this.time;r.speed*=.7}r.sync(t)}
  collisions(){for(let i=0;i<this.racers.length;i++)for(let j=i+1;j<this.racers.length;j++){const a=this.racers[i],b=this.racers[j],pd=Math.abs((a.progress-b.progress+.5)%1-.5);if(pd>.012||Math.abs(a.lane-b.lane)>1.4)continue;if(a.invulnerable>0||b.invulnerable>0)continue;const aw=a.r.stats[3],bw=b.r.stats[3],push=.25+Math.abs(a.speed-b.speed)*.015;a.lane=clamp(a.lane+(a.lane<=b.lane?-1:1)*push*bw/5,-5.7,5.7);b.lane=clamp(b.lane-(a.lane<=b.lane?-1:1)*push*aw/5,-5.7,5.7);if(a.r.kind!=='gorak')a.speed*=.91;if(b.r.kind!=='gorak')b.speed*=.91;if(a.r.kind==='nebulo')a.invulnerable=2;if(b.r.kind==='nebulo')b.invulnerable=2}}
  sorted(){return[...this.racers].sort((a,b)=>a.finished&&b.finished?a.finishTime-b.finishTime:a.finished?-1:b.finished?1:b.score()-a.score())}
  updateFinish(dt,t){for(const r of this.racers){r.speed*=Math.pow(.985,dt*60);r.progress=wrap(r.progress+r.speed/260*dt);r.sync(t)}if(this.player)this.cameraFollow(this.player,dt)}
  cameraFollow(r,dt){const s=this.track.sample(r.progress,r.lane),back=s.tangent.clone().multiplyScalar(-10),desired=s.position.clone().add(back).add(new THREE.Vector3(0,6.1+r.air,0)),look=s.position.clone().addScaledVector(s.tangent,7).add(new THREE.Vector3(0,1.1,0));this.camera.position.lerp(desired,1-Math.exp(-5.5*dt));this.look.lerp(look,1-Math.exp(-7*dt));this.camera.lookAt(this.look)}
  snapCamera(){if(!this.player)return;const s=this.track.sample(this.player.progress,this.player.lane);this.camera.position.copy(s.position).addScaledVector(s.tangent,-11).add(new THREE.Vector3(0,6,0));this.look.copy(s.position);this.camera.lookAt(this.look)}
  menuCamera(now){const a=now*.00005;this.camera.position.set(Math.cos(a)*68,40,Math.sin(a)*68);this.camera.lookAt(0,0,0)}
  pause(){if(!['race','countdown'].includes(this.state))return;this.beforePause=this.state;this.state='paused';this.input.reset();this.ui.showPause()}
  resume(){if(this.state!=='paused')return;this.state=this.beforePause;this.last=performance.now();this.ui.hidePause()}
  menu(){this.clear();this.state='menu';this.input.reset();this.ui.showMenu()}
  resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,w<720?1.25:1.55));this.camera.aspect=w/Math.max(1,h);this.camera.updateProjectionMatrix()}
}
function driveTarget(max,boost){return max*(boost>0?1.28:1)}
